# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresql-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-operator
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-viewer-role
rules:
- apiGroups:
  - postgres.flohansen
  resources:
  - postgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.flohansen
  resources:
  - postgresqls/status
  verbs:
  - get
